### ISSUE TITLE
Can't see the package in newer verion of UiPath

### ISSUE THREAD

**Issue by dev4s** [alexandretperez/Autossential#1]
Hi!
I'm just leaving information that maybe you should update the NuGet package for your library. On the UiPath Studio (Community Edition) I can't see your package, the version of UiPath is: 2021.10.0-beta.5978. I don't know about the "stable" release of UiPath. As I can see the packages that are made by UiPath (and some others) are having the .net5.0-windows7.0 lib version.

![image](https://user-images.githubusercontent.com/1382421/136674444-27674d27-ed67-4981-aa49-5dfd7edad925.png)
Your package

![image](https://user-images.githubusercontent.com/1382421/136674454-995b70d6-9e3e-4ca0-a289-93ffe115c5ed.png)
Sample UiPath.Box.Activities package

**Comment by alexandretperez** [comment]
Hi @dev4s,

To use Autossential and apparently any custom activities build by the community (marketplace) you need use the "Windows - Legacy" on the compatibility options instead of "Windows" or "Cross-platform".

The other options targets .NET 5.0 and the Windows Workflow Foundation was not ported to this version and never will (at least by Microsoft).

UiPath has the open source project called [CoreWF ](https://github.com/UiPath/CoreWF) where they are porting this.

By the tests that I was able to do, it seems that only UiPath's official packages has compatibility with newer versions of Studio.

If we try to use the CoreFW ([UiPath.Workflow](https://www.myget.org/feed/uipath-dev/package/nuget/UiPath.Workflow)) as a dependency, the package is recognized by package manager but when we try to install it we receive the message:

> Package 'xxxx' cannot be installed because it depends on package 'System.Activities'.
> Studio provides its own version of the package 'System.Activities' and restricts its installation as a dependency.

I'm not sure how to solve this issue with the resources available by now, but I hope that UiPath team will provide a way in a near future, otherwise, not only Autossential but many other community packages will not be compatible.

**Comment by alexandretperez** [comment]
The new version 3.0 (currently in preview) is compatible with Windows Legacy (Framework 461) and Windows (.NET 5.0).
This is a major new release and there are BREAKING CHANGES in relation to 2.x versions.
